batch_size: 4
iters: 40000

train_dataset:
  type: Dataset
  dataset_root: /root/autodl-tmp/dataset/RiverIce/IPCameraImage/3class/train
  train_path: /root/autodl-tmp/dataset/RiverIce/IPCameraImage/3class/train/train.txt
  num_classes: 3
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 1024]
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: /root/autodl-tmp/dataset/RiverIce/IPCameraImage/3class/val
  val_path: /root/autodl-tmp/dataset/RiverIce/IPCameraImage/3class/val/val.txt
  num_classes: 3
  transforms:
    - type: Normalize
  mode: val

optimizer:
  type: AdamW
  weight_decay: 0.01
  custom_cfg:
  - name: pos_embed
    weight_decay_mult: 0.0
  - name: head
    lr_multi: 10.0
  - name: bn
    weight_decay_mult: 0.0

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.0006
  end_lr: 0
  power: 1.0
  warmup_iters: 1500
  warmup_start_lr: 1.0e-6

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1]


model:
  type: PPMobileSeg
  num_classes: 3
  backbone:
    type: MobileSeg_Base
    inj_type: AAMSx8
    out_feat_chs: [64, 128, 192]
    pretrained: Null
  upsample: intepolate # During exportation, you need to change it to vim for using VIM